set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'

Plugin 'https://github.com/scrooloose/nerdtree'
Plugin 'https://github.com/kien/ctrlp.vim'
Plugin 'https://github.com/altercation/vim-colors-solarized'
Plugin 'https://github.com/rust-lang/rust.vim'
Plugin 'https://github.com/davidhalter/jedi-vim'


" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required
" To ignore plugin indent changes, instead use:
"filetype plugin on
"
" Brief help
" :PluginList       - lists configured plugins
" :PluginInstall    - installs plugins; append `!` to update or just :PluginUpdate
" :PluginSearch foo - searches for foo; append `!` to refresh local cache
" :PluginClean      - confirms removal of unused plugins; append `!` to auto-approve removal
"
" see :h vundle for more details or wiki for FAQ
" Put your non-Plugin stuff after this line


" Plugin specific configs
map <C-n> :NERDTreeToggle<CR>
let NERDTreeShowHidden=1

let g:clang_library_path='/usr/lib/llvm-3.8/lib/libclang-3.8.so.1'
au CompleteDone * pclose

let g:ctrlp_working_path_mode = 'ra'

" Tabstuff
set tabstop=4
set shiftwidth=4
set expandtab
set cindent
"set smartindent
autocmd FileType make setlocal noexpandtab

" Move lines
noremap <c-up> :call feedkeys( line('.')==1 ? '' : 'ddkP' )<CR>
noremap <c-down> ddp


set scrolloff=15
set number
set background=dark
set hlsearch
hi Search guibg=LightBlue
"<Ctrl-l> redraws the screen and removes any search highlighting.
nnoremap <silent> <C-l> :nohl<CR><C-l>


syntax on

" CPP syntax stuff
"let g:cpp_class_decl_highlight = 1

" Colors
syntax enable
set background=dark
colorscheme elflord

" Shell config because Vundle complains.
set shell=/bin/bash


let &t_SI = "\<Esc>[6 q"
let &t_SR = "\<Esc>[4 q"
let &t_EI = "\<Esc>[2 q"

